const baseURL = "https://tmdb-backend-iu1z.onrender.com";
const imageBaseURL = "/api/image";
const trendingEndpoint = "/api/trending";
const actionEndpoint = "/api/movies/action";
const comedyEndpoint = "/api/movies/comedy";
const horrorEndpoint = "/api/movies/horror";
const romanceEndpoint = "/api/movies/romance";
const documentaryEndpoint = "/api/movies/documentary";
const genresEndpoint = "/genre/movie/list";
export { baseURL , imageBaseURL , trendingEndpoint , actionEndpoint , comedyEndpoint , horrorEndpoint , romanceEndpoint , documentaryEndpoint , genresEndpoint  };